import 'package:hive/hive.dart';
import 'package:login/model/session_model.dart';

part 'course_model.g.dart'; // This will be generated by hive_generator

@HiveType(typeId: 0) // Unique typeId for this model
class Course {
  @HiveField(0)
  int id;

  @HiveField(1)
  String title;

  @HiveField(2)
  String? description;

  @HiveField(3)
  int levelId;

  @HiveField(4)
  String? image;

  @HiveField(5)
  int? hours;

  @HiveField(6)
  bool isRegistered;

  @HiveField(7)
  DateTime createdAt;

  @HiveField(8)
  DateTime updatedAt;

  @HiveField(9)
  List<Session> sessions;

  Course({
    required this.id,
    required this.title,
    required this.image,
    required this.hours,
    required this.isRegistered,
    this.description,
    required this.levelId,
    required this.createdAt,
    required this.sessions,
    required this.updatedAt,
  });

  factory Course.fromJson(Map<String, dynamic> json) {
    final data =
        json['course_sessions'] == null ? [] : json['course_sessions'] as List;
    List<Session> allSessions = data.map((e) => Session.fromJson(e)).toList();
    return Course(
      id: json['id'],
      title: json['title'],
      image: json['image'],
      sessions: allSessions,
      isRegistered: json['is_registered'] ?? false,
      hours: int.parse(json['hours'] ?? '0'),
      description: json['description'] ?? 'No Description',
      levelId: int.parse(json['level_id'].toString()),
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'level_id': levelId,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}
