import 'package:hive/hive.dart';

part 'session_model.g.dart'; // This will be generated by hive_generator

@HiveType(
    typeId: 1) // Unique typeId for this model (must be different from Course)
class Session {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final int courseId;

  @HiveField(2)
  final String sessionTitle;

  @HiveField(3)
  final String video;

  @HiveField(4)
  final DateTime createdAt;

  @HiveField(5)
  final DateTime updatedAt;

  Session({
    required this.id,
    required this.courseId,
    required this.sessionTitle,
    required this.video,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Session.fromJson(Map<String, dynamic> json) {
    return Session(
      id: int.parse(json['id'].toString()),
      courseId: int.parse(json['course_id'].toString()),
      sessionTitle: json['session_title'] ?? 'No title',
      video: json['video'],
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
    );
  }
}
