import 'package:hive/hive.dart';

part 'user_model.g.dart'; // This will be generated by hive_generator

@HiveType(
    typeId: 2) // Unique typeId for this model (must be different from Course)
class User {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String name;

  @HiveField(2)
  final String email;

  @HiveField(3)
  final String image;

  User({
    required this.id,
    required this.name,
    required this.email,
    required this.image,
  });

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: int.parse(json['id'].toString()),
      email: json['email'],
      image: json['image'] ?? '',
      name: json['name'],
    );
  }
}
